-- SnapClass — Database Schema (PostgreSQL / Supabase)
-- Fixed version: the original had syntax errors that would not
-- execute at all (trailing commas, misspelled keywords, a table
-- name mismatch, and column name mismatches in foreign keys).

-- Recommended: enables efficient similarity search on face/voice
-- embeddings (nearest-neighbor search with an index) instead of
-- pulling every row into Python and comparing manually. Supabase
-- supports this out of the box.
CREATE EXTENSION IF NOT EXISTS vector;

-- TEACHERS
CREATE TABLE teachers (
  teacher_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       TEXT UNIQUE NOT NULL,
  password_hash  TEXT NOT NULL,        -- store a bcrypt hash here, never the raw password
  name           TEXT,
  email          TEXT,
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- STUDENTS
-- FaceID is the PRIMARY login method. username/password are an OPTIONAL
-- backup credential (e.g. for logging in without a camera) — nullable,
-- unlike teachers who only have password login. Postgres's UNIQUE
-- constraint allows multiple NULL usernames without conflict, so students
-- who never set a backup password don't collide with each other.
-- ============================================================
CREATE TABLE students (
  student_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username         TEXT UNIQUE,           -- nullable: optional backup login
  password_hash    TEXT,                  -- nullable: bcrypt hash, only set if username is set
  name             TEXT NOT NULL,
  email            TEXT,
  roll_number      TEXT,

  -- Immediate, safe option (works with zero extra setup):
  face_embedding   JSONB,
  voice_embedding  JSONB,

  -- Recommended upgrade once the `vector` extension above is enabled.
  -- InsightFace/ArcFace embeddings are typically 512-dim; adjust to
  -- match whatever model you actually use.
  -- face_embedding_vec   VECTOR(512),
  -- voice_embedding_vec  VECTOR(256),

  created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- SUBJECTS / CLASSES
CREATE TABLE subjects (
  subject_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_code  TEXT UNIQUE NOT NULL,   -- UNIQUE added: this is almost certainly what your join-code links are built from
  name          TEXT DEFAULT 'Unknown',
  section       TEXT DEFAULT 'N/A',
  teacher_id    BIGINT REFERENCES teachers (teacher_id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- SUBJECT <-> STUDENT ENROLLMENT (junction table)
CREATE TABLE subject_students (
  subject_id   BIGINT REFERENCES subjects (subject_id) ON DELETE CASCADE,
  student_id   BIGINT REFERENCES students (student_id) ON DELETE CASCADE,
  enrolled_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (subject_id, student_id)   -- prevents the same student joining the same class twice
);

-- ATTENDANCE LOGS
-- One row per check-in event.
CREATE TABLE attendance_logs (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id        BIGINT REFERENCES subjects (subject_id) ON DELETE CASCADE,
  student_id        BIGINT REFERENCES students (student_id) ON DELETE CASCADE,
  logged_at         TIMESTAMPTZ DEFAULT NOW(),
  is_present        BOOL DEFAULT TRUE,
  method            TEXT DEFAULT 'face',   -- 'face' | 'voice' | 'manual' — lets you audit how each mark happened
  confidence_score  NUMERIC(5, 4)          -- e.g. 0.9821 — the recognition model's match confidence, for reviewing borderline cases
);

-- Speeds up the most common queries: "this student's history",
-- "this class's attendance today", and per-class trend reports.
CREATE INDEX idx_attendance_student ON attendance_logs (student_id);
CREATE INDEX idx_attendance_subject_time ON attendance_logs (subject_id, logged_at);

-- ROW LEVEL SECURITY
-- Supabase exposes every table via its REST API by default. Without
-- RLS enabled, anyone with your project's anon key can potentially
-- read biometric embeddings and attendance records directly. This
-- matters a lot here since you're storing biometric data, likely of
-- minors. Enabling RLS below BLOCKS all access until you write
-- policies — start locked down, then open up exactly what each role
-- needs (e.g. "a teacher can only see subjects they own").

ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE subject_students ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;

-- TODO: write real policies once your auth flow (Supabase Auth vs.
-- your own bcrypt/JWT login) is finalized. Example shape for later:
--
-- CREATE POLICY "Teachers can view their own subjects"
--   ON subjects FOR SELECT
--   USING (teacher_id = auth.uid());